trad:
    resource: "@TradBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    resource: @AppBundle/Controller/
    type:     annotation


